### ISSUE TITLE
Client/イベント編集時に日付いじると起きた

### ISSUE THREAD

**Issue by nisi0929** [Doer-org/google-cloud-challenge-2022#118]
多分サーバー側でなんかこのあたりの変更があったような気もします
<img width="1015" alt="スクリーンショット 2023-02-11 23 16 20" src="https://user-images.githubusercontent.com/70254634/218262871-c8b7aed0-c6dc-4958-ab55-b30ca781c015.png">

**Comment by nisi0929** [comment]
@RyushiAok 
一旦該当箇所コメントアウトしました
https://github.com/Doer-org/google-cloud-challenge-2022/blob/f6927cb7719dc9feb72ad991f2f4e8e5206d9e3e/client/src/core/utils/fptsHelper.ts#L18

**Comment by RyushiAok** [comment]
200番エラー問題は確か修正されたので，その箇所のコメントアウトは正しいはず．
