### ISSUE TITLE
確認モーダルのデザイン修正

### ISSUE THREAD

**Issue by nisi0929** [Doer-org/google-cloud-challenge-2022#63]

**Comment by nisi0929** [comment]
@mahiro72 
こっちに寄せる認識で大丈夫ですか？
https://www.figma.com/file/fs7U0LCirnSXPcACHW603W/google-cloud-challenges?node-id=32%3A382&t=yy1tWfnZw1YCy2By-0

**Comment by mahiro72** [comment]
okです！
